#!/usr/bin/env bash
# =============================================================================
# check-versions.sh - Comprehensive version consistency checker
# =============================================================================
# Usage: ./scripts/check-versions.sh [--fix]
#
# Checks ALL version references in the codebase for consistency:
#   - Cargo.toml (source of truth)
#   - wasm/package.json
#   - pkg/package.json (generated)
#   - README.md
#   - book/src/getting-started.md
#   - CHANGELOG.md
#   - examples/cli/*.sh
#   - tests/*.rs
#   - llms.txt / llms-full.txt
#   - export.json test files
#
# Exit codes:
#   0 - All versions consistent
#   1 - Version mismatches found
#   2 - Error occurred
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

FIX_MODE=false

for arg in "$@"; do
    case $arg in
        --fix) FIX_MODE=true ;;
        --help|-h)
            echo "Usage: $0 [--fix]"
            echo ""
            echo "Options:"
            echo "  --fix    Auto-fix version mismatches"
            echo "  --help   Show this help"
            exit 0
            ;;
    esac
done

cd "${PROJECT_ROOT}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Counters
MISMATCHES=0
CHECKED=0
FIXED=0

# Get version from Cargo.toml (source of truth)
CARGO_VERSION=$(grep -m1 '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
if [[ -z "$CARGO_VERSION" ]]; then
    echo -e "${RED}✗ Could not extract version from Cargo.toml${NC}"
    exit 2
fi

MAJOR_MINOR=$(echo "$CARGO_VERSION" | cut -d. -f1,2)

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Version Consistency Checker${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Source of truth: Cargo.toml = ${CARGO_VERSION}"
echo "Major.minor:     ${MAJOR_MINOR}"
echo ""

# Helper function to check a version reference
check_version() {
    local file="$1"
    local expected="$2"
    local pattern="$3"
    local description="$4"
    local extract_cmd="$5"

    if [[ ! -f "$file" ]]; then
        echo -e "${YELLOW}⊘${NC} $description: file not found ($file)"
        return 0
    fi

    ((CHECKED++)) || true

    local current
    current=$(eval "$extract_cmd" 2>/dev/null || echo "")

    if [[ -z "$current" ]]; then
        echo -e "${YELLOW}?${NC} $description: pattern not found"
        return 0
    fi

    if [[ "$current" == "$expected" ]]; then
        echo -e "${GREEN}✓${NC} $description: $current"
        return 0
    else
        echo -e "${RED}✗${NC} $description: $current (expected $expected)"
        ((MISMATCHES++)) || true
        
        if $FIX_MODE; then
            sed -i "$pattern" "$file" 2>/dev/null || true
            echo -e "${CYAN}↻${NC} Fixed: $description"
            ((FIXED++)) || true
        fi
        return 1
    fi
}

echo -e "${CYAN}→ Core Package Files${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 1. Cargo.toml (source of truth - just verify it exists)
echo -e "${GREEN}✓${NC} Cargo.toml: $CARGO_VERSION (source of truth)"
((CHECKED++)) || true

# 2. wasm/package.json - exact version
check_version "wasm/package.json" "$CARGO_VERSION" \
    "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"${CARGO_VERSION}\"/" \
    "wasm/package.json" \
    'grep "\"version\"" wasm/package.json | head -1 | sed "s/.*: *\"\([0-9.]\+\)\".*/\1/"'

# 3. pkg/package.json - exact version (generated file, may be gitignored)
# Note: pkg/ is generated by wasm-pack, skip if not tracked
if git ls-files pkg/package.json 2>/dev/null | grep -q .; then
    check_version "pkg/package.json" "$CARGO_VERSION" \
        "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"${CARGO_VERSION}\"/" \
        "pkg/package.json" \
        'grep "\"version\"" pkg/package.json | head -1 | sed "s/.*: *\"\([0-9.]\+\)\".*/\1/"'
elif [[ -f "pkg/package.json" ]]; then
    echo -e "${YELLOW}⊘${NC} pkg/package.json: generated file (not tracked in git)"
fi

# 4. Cargo.lock - should have the same version
check_version "Cargo.lock" "$CARGO_VERSION" \
    "" \
    "Cargo.lock" \
    'grep "name = \"chaotic_semantic_memory\"" Cargo.lock -A1 | grep version | head -1 | sed "s/version = \"\(.*\)\"/\1/"'

echo ""
echo -e "${CYAN}→ Documentation Files${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 5. README.md - major.minor for semver compatibility
check_version "README.md" "$MAJOR_MINOR" \
    "s/chaotic_semantic_memory = { version = \"[0-9]\+\.[0-9]\+\"/chaotic_semantic_memory = { version = \"${MAJOR_MINOR}\"/g" \
    "README.md (installation)" \
    'grep "chaotic_semantic_memory = { version" README.md | head -1 | sed "s/.*version = \"\([0-9.]\+\)\".*/\1/"'

# 6. book/src/getting-started.md - major.minor
check_version "book/src/getting-started.md" "$MAJOR_MINOR" \
    "s/chaotic_semantic_memory = { version = \"[0-9]\+\.[0-9]\+\"/chaotic_semantic_memory = { version = \"${MAJOR_MINOR}\"/g" \
    "book/src/getting-started.md" \
    'grep "chaotic_semantic_memory = { version" book/src/getting-started.md | head -1 | sed "s/.*version = \"\([0-9.]\+\)\".*/\1/"'

# 7. CHANGELOG.md - check for current version header
if [[ -f "CHANGELOG.md" ]]; then
    ((CHECKED++)) || true
    if grep -q "## \[$CARGO_VERSION\]" CHANGELOG.md; then
        echo -e "${GREEN}✓${NC} CHANGELOG.md: has [$CARGO_VERSION] section"
    else
        echo -e "${YELLOW}?${NC} CHANGELOG.md: no [$CARGO_VERSION] section (may be unreleased)"
    fi
fi

# 8. llms.txt
check_version "llms.txt" "$CARGO_VERSION" \
    "" \
    "llms.txt" \
    'grep -oE "[0-9]+\.[0-9]+\.[0-9]+" llms.txt | head -1'

# 9. llms-full.txt
check_version "llms-full.txt" "$CARGO_VERSION" \
    "" \
    "llms-full.txt" \
    'grep -oE "[0-9]+\.[0-9]+\.[0-9]+" llms-full.txt | head -1'

echo ""
echo -e "${CYAN}→ Test & Example Files${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 10. examples/cli/*.sh - check for version in JSON
for f in examples/cli/*.sh; do
    if [[ -f "$f" ]]; then
        ver=$(grep -oE '"version"[[:space:]]*:[[:space:]]*"[0-9.]+"' "$f" 2>/dev/null | head -1 | sed 's/.*"\([0-9.]\+\)".*/\1/' || true)
        if [[ -n "$ver" ]]; then
            ((CHECKED++)) || true
            if [[ "$ver" == "$CARGO_VERSION" ]]; then
                echo -e "${GREEN}✓${NC} $f: $ver"
            else
                echo -e "${RED}✗${NC} $f: $ver (expected $CARGO_VERSION)"
                ((MISMATCHES++)) || true
                if $FIX_MODE; then
                    sed -i "s/\"version\"[[:space:]]*:[[:space:]]*\"[0-9.]\+\"/\"version\": \"${CARGO_VERSION}\"/g" "$f"
                    echo -e "${CYAN}↻${NC} Fixed: $f"
                    ((FIXED++)) || true
                fi
            fi
        fi
    fi
done

# 11. tests/*.rs - check for version in JSON strings
for f in tests/*.rs; do
    if [[ -f "$f" ]]; then
        ver=$(grep -oE '"version"[[:space:]]*:[[:space:]]*"[0-9.]+"' "$f" 2>/dev/null | head -1 | sed 's/.*"\([0-9.]\+\)".*/\1/' || true)
        if [[ -n "$ver" ]]; then
            ((CHECKED++)) || true
            if [[ "$ver" == "$CARGO_VERSION" ]]; then
                echo -e "${GREEN}✓${NC} $f: $ver"
            else
                echo -e "${RED}✗${NC} $f: $ver (expected $CARGO_VERSION)"
                ((MISMATCHES++)) || true
                if $FIX_MODE; then
                    sed -i "s/\"version\"[[:space:]]*:[[:space:]]*\"[0-9.]\+\"/\"version\": \"${CARGO_VERSION}\"/g" "$f"
                    echo -e "${CYAN}↻${NC} Fixed: $f"
                    ((FIXED++)) || true
                fi
            fi
        fi
    fi
done

echo ""
echo -e "${CYAN}→ Generated/Test JSON Files${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 12. export.json (if exists)
if [[ -f "export.json" ]]; then
    check_version "export.json" "$CARGO_VERSION" \
        "s/\"version\": \"[0-9.]\+\"/\"version\": \"${CARGO_VERSION}\"/" \
        "export.json" \
        'grep "\"version\"" export.json | head -1 | sed "s/.*: *\"\([0-9.]\+\)\".*/\1/"'
fi

# 13. csm_test.json (if exists)
if [[ -f "csm_test.json" ]]; then
    check_version "csm_test.json" "$CARGO_VERSION" \
        "s/\"version\": \"[0-9.]\+\"/\"version\": \"${CARGO_VERSION}\"/" \
        "csm_test.json" \
        'grep "\"version\"" csm_test.json | head -1 | sed "s/.*: *\"\([0-9.]\+\)\".*/\1/"'
fi

# 14. pkg/README.md (if exists and tracked)
if git ls-files pkg/README.md 2>/dev/null | grep -q .; then
    ver=$(grep "| Version" pkg/README.md 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || true)
    if [[ -n "$ver" ]]; then
        ((CHECKED++)) || true
        if [[ "$ver" == "$CARGO_VERSION" ]]; then
            echo -e "${GREEN}✓${NC} pkg/README.md: $ver"
        else
            echo -e "${RED}✗${NC} pkg/README.md: $ver (expected $CARGO_VERSION)"
            ((MISMATCHES++)) || true
        fi
    fi
elif [[ -f "pkg/README.md" ]]; then
    echo -e "${YELLOW}⊘${NC} pkg/README.md: generated file (not tracked in git)"
fi

echo ""
echo -e "${CYAN}→ Dependency Versions (info only)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Show key dependency versions (info only, not checked)
SERDE_VER=$(grep 'serde = ' Cargo.toml | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "unknown")
TOKIO_VER=$(grep 'tokio = ' Cargo.toml | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "unknown")
RAND_VER=$(grep 'rand = ' Cargo.toml | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "unknown")

echo "  serde: $SERDE_VER"
echo "  tokio: $TOKIO_VER"
echo "  rand:  $RAND_VER"

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Summary${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Files checked:   ${CHECKED}"
echo "Mismatches:      ${MISMATCHES}"
if $FIX_MODE; then
    echo "Files fixed:     ${FIXED}"
fi
echo ""

if [[ "$MISMATCHES" -gt 0 ]]; then
    if $FIX_MODE; then
        echo -e "${YELLOW}⚠ Fixed ${FIXED} version mismatch(es)${NC}"
        echo ""
        echo "Run these commands to complete:"
        echo "  ./scripts/sync-docs.sh"
        echo "  git add -A && git commit -m 'fix: sync versions to ${CARGO_VERSION}'"
    else
        echo -e "${RED}✗ Found ${MISMATCHES} version mismatch(es)${NC}"
        echo ""
        echo "Run with --fix to auto-fix, or manually update the files above."
        echo "Or run: ./scripts/sync-docs.sh"
    fi
    exit 1
else
    echo -e "${GREEN}✓ All versions consistent with Cargo.toml (${CARGO_VERSION})${NC}"
    exit 0
fi
