name: Dist

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dist:
    name: Dist (${{ matrix.platform }}-${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            arch: x64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: linux
            arch: arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - platform: macos
            arch: arm64
            runner: macos-latest
            target: aarch64-apple-darwin
          - platform: macos
            arch: x64
            runner: macos-latest
            target: x86_64-apple-darwin
          - platform: windows
            arch: x64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.1.7
        with:
          fetch-depth: 0
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          cache: false
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cross-compilation linker (Linux arm64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
      - name: Install cargo-dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.27.0/cargo-dist-installer.sh | sh
      - name: Run cargo-dist
        run: cargo dist build --tag ${{ github.ref_name }} --target ${{ matrix.target }}
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/dist/*
