name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: secret-scan-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@69efee0fbff412f1a22a47da1ea37d962f8adca7 # v4.1.7
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secretlint:
    name: Secretlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@69efee0fbff412f1a22a47da1ea37d962f8adca7 # v4.1.7
      - name: Secretlint
        uses: secretlint/secretlint-action@679644f59a3854a01c40f2302381285600c3b06e # v1.1.1
